import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
const factory=process.env.TEST_FACTORY_ORIGIN??'http://127.0.0.1:5181';
const browser=await chromium.launch({channel:'chrome',headless:true});
try{
  const context=await browser.newContext({acceptDownloads:true,viewport:{width:1440,height:1000}}),page=await context.newPage(),errors=[];
  page.on('pageerror',error=>errors.push(error.message));
  await context.grantPermissions(['clipboard-read','clipboard-write'],{origin:'http://127.0.0.1:5173'});
  await page.goto('http://127.0.0.1:5173?edit=1');await page.waitForFunction(()=>window.marbleStudio);
  const connect=()=>page.evaluate(origin=>document.querySelector('.factory-link').href=origin+'/factory.html',factory);await connect();
  assert.equal(await page.locator('#record').isVisible(),false);
  await page.locator('#count').selectOption('8');
  await page.locator('#open-balls').click();await page.locator('[data-name="0"]').fill('Studio Transfer');await page.locator('[data-name="0"]').press('Tab');await page.locator('[data-close="balls-dialog"]').click();
  await page.locator('#music-title').click();await page.locator('#music-mode').selectOption('fixed');await page.locator('#music-track').selectOption('cipher');
  await page.locator('#studio-works').click();await page.locator('#work-name').fill('Ülkeler yarışı');await page.locator('#work-save').click();
  await page.waitForFunction(()=>document.querySelector('#works-list').children.length===1&&document.querySelector('#works-message').textContent.includes('kaydedildi'));
  await page.locator('[data-action=copy]').click();await page.waitForFunction(()=>document.querySelectorAll('[data-action=open]').length===2);
  await page.locator('#works-dialog [data-wb-close]').click();
  await page.locator('.studio-actions > summary').click();const download=page.waitForEvent('download');await page.locator('#studio-backup').click();const saved=await download;
  const text=await readFile(await saved.path(),'utf8'),backup=JSON.parse(text);assert.equal(backup.works.length,2);assert.match(text,/Studio Transfer/);
  await page.locator('#studio-backup-file').setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from('{bad')});await page.waitForFunction(()=>document.querySelector('#toast').textContent.includes('okunamadı'));
  assert.equal(await page.evaluate(()=>window.marbleStudio.getState().names[0]),'Studio Transfer');
  await page.locator('#studio-backup-file').setInputFiles({name:'restore.json',mimeType:'application/json',buffer:Buffer.from(text)});await page.waitForEvent('load');await page.waitForFunction(()=>window.marbleStudio);await connect();
  await page.locator('#nav-arena').click();await page.locator('#studio-works').click();await page.locator('[data-action=open]').first().click();
  await page.waitForFunction(()=>!document.querySelector('#works-dialog').open);
  const restored=await page.evaluate(()=>window.marbleStudio.getState());assert.equal(restored.mode,'track');assert.equal(restored.count,8);assert.equal(restored.names[0],'Studio Transfer');assert.equal(await page.locator('#music-track').inputValue(),'cipher');
  await page.locator('#studio-export').click();await page.waitForFunction(()=>document.querySelector('#video-submit').textContent==='Videoyu hazırla'&&!document.querySelector('#video-submit').disabled);
  assert.equal(context.pages().length,1,'Export stays in the same window');assert.equal(await page.locator('#video-advanced').getAttribute('open'),null);
  await page.locator('[name=orientation][value=landscape]').check();await page.locator('#video-advanced summary').click();await page.locator('[name=fps]').selectOption('60');
  await page.screenshot({path:'artifacts/easy-export-desktop.png',fullPage:true});await page.locator('#video-dialog [data-wb-close]').click();
  await page.locator('#studio-export').click();await page.waitForFunction(()=>document.querySelector('#video-submit').textContent==='Videoyu hazırla');assert.equal(await page.locator('[name=orientation][value=landscape]').isChecked(),true);assert.equal(await page.locator('[name=fps]').inputValue(),'60');
  let sent;await page.route(factory+'/api/queue',async route=>{sent=route.request().postDataJSON();await route.fulfill({json:{ok:true},headers:{'Access-Control-Allow-Origin':'http://127.0.0.1:5173'}});});
  await page.locator('#video-submit').click();await page.waitForFunction(()=>document.querySelector('#videos-dialog').open);
  assert.equal(sent.source.project.ballNames[0],'Studio Transfer');assert.equal(sent.source.music.track,'cipher');assert.equal(sent.fps,60);assert.equal(sent.strategy,'exact');
  await page.unroute(factory+'/api/queue');await page.locator('#videos-dialog [data-wb-close]').click();
  await page.locator('#nav-statistics').click();await page.locator('#statistics-duration').selectOption('15');await page.locator('#statistics-heading').fill('Arşiv testi');await page.locator('#statistics-heading').dispatchEvent('change');
  await page.locator('#studio-export').click();await page.waitForFunction(()=>document.querySelector('#video-submit').textContent==='Videoyu hazırla');
  assert.equal(await page.locator('[name=orientation][value=landscape]').isChecked(),true);assert.equal(await page.locator('[name=strategy] option[value=variations]').evaluate(o=>o.disabled),true);
  await page.locator('#video-advanced summary').click();await page.locator('[name=resolution]').selectOption('720');
  await page.setViewportSize({width:390,height:844});assert.ok(await page.evaluate(()=>document.querySelector('#video-dialog').scrollWidth<=innerWidth));await page.screenshot({path:'artifacts/easy-export-mobile.png',fullPage:true});
  await page.locator('#video-submit').click();await page.waitForFunction(()=>document.querySelector('#videos-dialog').open);
  await page.waitForFunction(()=>document.querySelector('#videos-list video'),{},{timeout:180000});
  const video=page.locator('#videos-list video').first();await video.evaluate(v=>v.load());await page.waitForFunction(()=>document.querySelector('#videos-list video')?.readyState>=1);
  const media=await video.evaluate(v=>({width:v.videoWidth,height:v.videoHeight,duration:v.duration}));assert.equal(media.width,1280);assert.equal(media.height,720);assert.ok(media.duration>=17);
  await video.evaluate(v=>{v.currentTime=8;});await page.waitForFunction(()=>Math.abs(document.querySelector('#videos-list video').currentTime-8)<.2);
  await page.locator('[data-job-action=copy]').first().click();assert.equal(await page.evaluate(()=>navigator.clipboard.readText()),'Arşiv testi');
  let revealed;await page.route(factory+'/api/reveal',async route=>{revealed=route.request().postDataJSON().id;await route.fulfill({json:{ok:true},headers:{'Access-Control-Allow-Origin':'http://127.0.0.1:5173'}});});await page.locator('[data-job-action=reveal]').first().click();await page.waitForTimeout(100);assert.ok(revealed);
  const videoDownload=page.waitForEvent('download');await page.locator('#videos-list a[download]').first().click();assert.match((await videoDownload).suggestedFilename(),/video.mp4/);
  assert.ok(await page.evaluate(()=>document.querySelector('#videos-dialog').scrollWidth<=innerWidth));await page.screenshot({path:'artifacts/easy-videos-mobile.png',fullPage:true});
  await page.locator('#videos-filter').selectOption('cancelled');await page.waitForFunction(()=>!document.querySelector('#videos-list video')&&document.querySelector('#videos-list .wb-empty'));
  await page.locator('#videos-filter').selectOption('all');await page.waitForFunction(()=>document.querySelector('#videos-list video'));
  assert.deepEqual(errors,[]);console.log('PASS: saved works/copy/open with roster/music, backup restore, one-window MP4, remembered presets, mobile, real video generation, preview/seek/download, copy title and folder action.');
}finally{await browser.close();}
