import assert from 'node:assert/strict';
import {mkdtemp,readFile,writeFile} from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {contentKeys,createRepetitionGuard,openRepetitionLedger,repetitionEntry} from '../scripts/repetition-guard.mjs';
import {planAutomatic,automaticCandidate} from '../scripts/production-automation.mjs';
import {validateBatch} from '../src/factory-recipes.js';
const now=Date.UTC(2030,0,1),day=86400000;
const recipe={mode:'track',seed:7,count:6,sequence:[{type:'pulse',settings:{speed:1}}]};
const original={id:'original',recipe,completedAt:new Date(now-100*day).toISOString()};
const fillers=Array.from({length:300},(_,i)=>({id:'filler-'+i,recipe:{...recipe,seed:100+i,sequence:[{type:'slalom'}]},completedAt:new Date(now-99*day+i).toISOString()}));
const all=[original,...fillers],changedSeed={...recipe,seed:8};
assert.equal(createRepetitionGuard(all,[],now).check(recipe).allowed,false,'Exact content remains blocked after the cooldown');
assert.equal(createRepetitionGuard(all,[],now).check(changedSeed).allowed,true,'Both 90 days and 300 intervening videos have elapsed');
assert.equal(createRepetitionGuard([original],[],now).check(changedSeed).allowed,false,'Age alone is insufficient');
assert.equal(createRepetitionGuard([{...original,completedAt:new Date(now-day).toISOString()},...fillers],[],now).check(changedSeed).allowed,false,'Video count alone is insufficient');
assert.equal(createRepetitionGuard([original],[],now).check({...recipe,music:{track:'new'},name:'Retitled',language:'en'}).allowed,false);
assert.equal(contentKeys({...recipe,sequence:[{type:'pulse',settings:{b:2,a:1}}]}).exact,contentKeys({...recipe,sequence:[{settings:{a:1,b:2},type:'pulse'}]}).exact,'Object order cannot bypass identity');
const stats={mode:'statistics',statistics:{csv:'Year,A,B\n2000,1,2\n2001,3,4'}};
const statsGuard=createRepetitionGuard([{id:'stat',recipe:stats,completedAt:original.completedAt}],[],now);
assert.equal(statsGuard.check({...stats,statistics:{...stats.statistics,heading:'New title',duration:60}}).allowed,false);
assert.equal(statsGuard.check({...stats,statistics:{csv:'Year,A,B\n2000,1,2\n2001,5,4'}}).allowed,true);
assert.equal(statsGuard.check({mode:'statistics',statistics:{csv:'Year;b;a\n2001;4;3\n2000;2;1'}}).allowed,false,'Reordering and formatting the same data does not create new content');
const root=await mkdtemp(path.join(os.tmpdir(),'marble-repeat-'));
let ledger=await openRepetitionLedger(root,[original]);
assert.equal(ledger.entries().length,1);
ledger=await openRepetitionLedger(root,[]); // Main job history can be archived independently.
assert.equal(createRepetitionGuard([],ledger.entries(),now).check(recipe).allowed,false);
await writeFile(path.join(root,'repetition-ledger.json'),'{broken');
ledger=await openRepetitionLedger(root,[]);assert.equal(ledger.entries().length,1,'Valid backup restores protection');
await writeFile(path.join(root,'repetition-ledger.json.bak'),'{broken');
await assert.rejects(openRepetitionLedger(root,[]),/hafızası/,'Never silently reset a damaged ledger');
const exhausted=[];
for(const theme of ['ice','lava','aurora','gold','candy','cosmic'])for(const variant of ['classic','avalanche','precision','burst'])exhausted.push({id:theme+'-'+variant,recipe:{mode:'spiral',seed:1,count:1,theme,variant},completedAt:new Date().toISOString()});
const guard=createRepetitionGuard(exhausted);
await assert.rejects(planAutomatic(validateBatch({automatic:true,automaticMode:'spiral',count:1}),exhausted,path.resolve('.'),guard),e=>e.code==='REPETITION_LIMIT'&&e.nonRetryable);
const planned=await planAutomatic(validateBatch({automatic:true,count:1}),exhausted,path.resolve('.'),guard);
assert.notEqual(planned.modes[0],'spiral','Automatic choice skips exhausted spiral styles');
const candidate=automaticCandidate(planned,42,exhausted,[],guard);assert.ok(guard.check(candidate).allowed);
assert.equal(createRepetitionGuard([original],[],now,'original').check(recipe).allowed,true,'A failed job can resume without blocking itself');
console.log('PASS: permanent content identity, 90-day AND 300-video cooldown, cosmetic changes, updated statistics, archive/restart persistence, backup recovery, fail-closed corruption, exhausted styles and automatic fallback.');
