import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import fs from 'node:fs';
fs.mkdirSync('artifacts',{recursive:true});
const browser=await chromium.launch({channel:'chrome',headless:true});
try {
  const page=await browser.newPage({viewport:{width:1440,height:1100}}),errors=[];
  const shared=[];await page.route('**/api/import-video',async route=>{const request=route.request();if(request.method()==='OPTIONS'){await route.fulfill({status:204,headers:{'Access-Control-Allow-Origin':'http://127.0.0.1:5173','Access-Control-Allow-Methods':'POST, OPTIONS','Access-Control-Allow-Headers':'Content-Type, X-Marble-Mode, X-Marble-Title'}});return;}shared.push({mode:request.headers()['x-marble-mode'],bytes:request.postDataBuffer()?.length??0});await route.fulfill({json:{ok:true,id:'test-recording'},headers:{'Access-Control-Allow-Origin':'http://127.0.0.1:5173'}});});
  page.on('pageerror',error=>errors.push(error.message));
  await page.goto('http://127.0.0.1:5173?edit=1');await page.waitForFunction(()=>window.marbleStudio);
  const course=await page.evaluate(()=>window.marbleStudio.getState().sections);
  const state=()=>page.evaluate(()=>window.marbleStudio.getStatisticsState());
  await page.locator('#nav-statistics').click();
  assert.equal(await page.locator('#track-view').isVisible(),false);
  assert.equal(await page.locator('#watch-view').isVisible(),false);
  assert.equal((await state()).ranking[0].name,'Atlas');
  await page.screenshot({path:'artifacts/statistics-desktop.png',fullPage:true});
  await page.locator('#statistics-play').click();
  await page.waitForFunction(()=>window.marbleStudio.getStatisticsState().progress>.01);
  await page.locator('#statistics-play').click();
  const paused=(await state()).progress;await page.waitForTimeout(120);assert.equal((await state()).progress,paused);
  await page.locator('#statistics-seek').fill('1');assert.equal((await state()).ranking[0].name,'Luna');
  await page.locator('#statistics-reset').click();assert.equal((await state()).year,2000);
  await page.locator('#statistics-csv').fill('Yıl,A,B\n2000,1,2\n2001,,4');
  await page.locator('#statistics-apply').click();assert.match(await page.locator('#statistics-data-status').innerText(),/geçersiz/);
  assert.equal((await state()).names.length,10,'Invalid imports preserve the applied data');
  const csv='Yıl,Alfa,Beta,Gama\n2010,10,30,0\n2015,40,20,15\n2020,80,50,40';
  await page.locator('#statistics-file').setInputFiles({name:'veriler.csv',mimeType:'text/csv',buffer:Buffer.from(csv)});
  await page.waitForFunction(()=>window.marbleStudio.getStatisticsState().names.length===3);
  await page.locator('#statistics-heading').fill('Yıllara göre değişim');
  await page.locator('#statistics-source').fill('Kendi veri tablom');
  await page.locator('#statistics-unit').fill('milyon');
  await page.locator('#statistics-duration').selectOption('15');
  await page.locator('#statistics-seek').fill('0.5');
  assert.equal((await state()).year,2015);assert.equal((await state()).ranking[0].name,'Alfa');
  const csvDownload=page.waitForEvent('download');await page.locator('#statistics-export').click();
  const exported=await csvDownload;await exported.saveAs('artifacts/statistics-data.csv');
  assert.equal(fs.readFileSync('artifacts/statistics-data.csv','utf8').replace(/^\uFEFF/,''),csv);
  await page.reload();await page.waitForFunction(()=>window.marbleStudio);await page.locator('#nav-statistics').click();
  assert.deepEqual((await state()).names,['Alfa','Beta','Gama']);
  assert.equal(await page.locator('#statistics-heading').inputValue(),'Yıllara göre değişim');
  assert.equal(await page.locator('#statistics-source').inputValue(),'Kendi veri tablom');
  await page.locator('#statistics-play').click();await page.locator('#nav-track').click();
  assert.equal((await state()).playing,false);
  assert.deepEqual(await page.evaluate(()=>window.marbleStudio.getState().sections),course);
  await page.locator('#nav-statistics').click();
  await page.setViewportSize({width:390,height:844});
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Mobile layout has no horizontal overflow');
  await page.screenshot({path:'artifacts/statistics-mobile.png',fullPage:true});
  await page.setViewportSize({width:1440,height:1100});
  const video=page.waitForEvent('download',{timeout:45000});await page.locator('#statistics-webm-options').evaluate(el=>el.open=true);await page.locator('#statistics-record').click();
  assert.equal((await state()).recording,true);
  for(const id of ['nav-track','nav-arena','statistics-apply','statistics-seek'])assert.equal(await page.locator('#'+id).isDisabled(),true,id);
  await page.evaluate(()=>document.querySelector('#nav-track').onclick());
  assert.equal(await page.locator('#statistics-view').isVisible(),true,'Navigation guard protects recording');
  await(await video).saveAs('artifacts/statistics-race.webm');
  assert.equal((await state()).recording,false);assert.equal((await state()).progress,1);
  assert.ok(fs.statSync('artifacts/statistics-race.webm').size>50000);
  await page.waitForTimeout(100);assert.equal(shared[0]?.mode,'statistics');assert.ok(shared[0]?.bytes>50000,'Statistics recordings enter the shared-video queue');
  await page.evaluate(()=>{const video=document.createElement('video');video.id='statistics-test-video';video.src='/artifacts/statistics-race.webm';video.muted=true;document.body.append(video);});
  await page.waitForFunction(()=>document.querySelector('#statistics-test-video').readyState>=1);
  assert.deepEqual(await page.locator('#statistics-test-video').evaluate(video=>[video.videoWidth,video.videoHeight]),[1920,1080]);
  await page.locator('#statistics-test-video').evaluate(video=>video.remove());
  await page.locator('#statistics-canvas').screenshot({path:'artifacts/statistics-final.png'});
  assert.equal(await page.locator('#nav-track').isDisabled(),false);
  await page.evaluate(()=>{
    const canvas=document.querySelector('#statistics-canvas'),capture=canvas.captureStream;
    canvas.captureStream=()=>{throw new Error('Simulated recording failure');};
    try{document.querySelector('#statistics-record').onclick();}finally{canvas.captureStream=capture;}
  });
  assert.equal((await state()).recording,false);assert.equal(await page.locator('#nav-track').isDisabled(),false);
  await page.locator('#statistics-webm-options').evaluate(el=>el.open=true);await page.locator('#statistics-record').click();
  await page.waitForFunction(()=>window.marbleStudio.getStatisticsState().progress>.1);
  const early=page.waitForEvent('download').catch(async error=>{throw new Error(`${error.message}; ${await page.locator('#toast').innerText()}; ${JSON.stringify(await state())}`);});
  await page.locator('#statistics-webm-options').evaluate(el=>el.open=true);await page.locator('#statistics-record').click();await early;
  assert.equal((await state()).recording,false);assert.ok((await state()).progress<1);
  await page.locator('#nav-track').click();await page.locator('#pause').click();
  await page.waitForFunction(()=>window.marbleStudio.getState().time>.1);
  await page.locator('#nav-statistics').click();
  assert.equal(await page.evaluate(()=>window.marbleStudio.getState().paused),true);
  assert.deepEqual(errors,[]);
  console.log('PASS: new tab, playback/pause/seek, leader changes, invalid data preservation, CSV import/export, persistence, independent course, mobile layout, recording locks and automatic 1920x1080 video.');
}finally{await browser.close();}
